### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by OiYouYeahYou**
* Install prettier
* Eslint fix and alter
* Make pretty

### CODE REVIEW

**Comment by datitisev** [comment]
Is there a reason why we are using prettier with eslint instead of by itself?

**Comment by OiYouYeahYou** [comment]
How do you mean? I have ran prettier independently of eslint in this case. But the issue at hand is that some of the elsint configs were conflicting with how prettier formats. Therefore I had to alter eslint to harmonise with prettier.

Or do you mean why didn't I use a prettier plugin for eslint? Which I could do if you wish

**Comment by datitisev** [comment]
@OiYouYeahYou I'd rather just replace ESLint with Prettier. I don't really care for the current ESLint configuration, you can ignore that. I apologize if I made you spend more time on it that one needed to.

**Comment by datitisev** [comment]
Oh, I just realized I never merged this. I apologize for that, as I won't be able to merge this because of a bunch of local changes that would require many merge conflicts to be resolved.

Really sorry about that. Thanks for the PR though. 😕 ❤️

**Comment by OiYouYeahYou** [comment]
A merge conflict would be easy to solve though

**Comment by OiYouYeahYou** [comment]
Actually, what conflicts, there are no commits since my last PR

**Comment by datitisev** [comment]
The conflicts were going to occur after I tried to merge my changes with these, as I edited a ton of files. Those changes have now been pushed. I apologize for wasting your time with this PR.

**Pull request closed without merging**
